steps:
  # Trinn for 책 bygge Flask-appen
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'api'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-api:$COMMIT_SHA', '.']

  # Trinn for 책 bygge Discord-botten
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'bot'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/discord-bot:$COMMIT_SHA', '.']

  # Trinn for 책 deploye Flask-appen til Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'flask-api-service',
      '--image', 'gcr.io/$PROJECT_ID/flask-api:$COMMIT_SHA',
      '--platform', 'managed',
      '--region', 'europe-north1',
      '--allow-unauthenticated',
      '--update-env-vars', 'FLASK_API_URL=$(FLASK_API_URL)'
    ]
    options:
      logging: CLOUD_LOGGING_ONLY

  # Trinn for 책 deploye Discord-botten til Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'discord-bot-service',
      '--image', 'gcr.io/$PROJECT_ID/discord-bot:$COMMIT_SHA',
      '--platform', 'managed',
      '--region', 'europe-north1',
      '--allow-unauthenticated',
      '--set-env-vars', 'CLIENT_TOKEN=$(CLIENT_TOKEN),CLIENT_ID=$(CLIENT_ID),GUILD_ID=$(GUILD_ID)'
    ]
    options:
      logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/flask-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/discord-bot:$COMMIT_SHA'
