version: '3.8'

services:
  flask_api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    networks:
      - my_network

  discord_bot:
    build:
      context: ./bot
    networks:
      - my_network
    env_file:
      - ./bot/.env

networks:
  my_network:
    driver: bridge
