"""stuff

Revision ID: aa920dda8ba3
Revises: d1c6700eb7e5
Create Date: 2025-09-21 23:58:23.442723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa920dda8ba3'
down_revision = 'd1c6700eb7e5'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('ledger_entry')
    op.drop_table('company')
    op.drop_table('company_transaction_details')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Company',
    sa.Column('CompanyID', sa.Integer(), nullable=False),
    sa.Column('ExternalID', sa.String(length=36), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('OwnerID', sa.Integer(), server_default='-1', nullable=False),
    sa.Column('Balance', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('LastTrygdClaim', sa.DateTime(), nullable=True),
    sa.Column('TrygdAmount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('CompanyID'),
    sa.UniqueConstraint('Name'),
    sa.UniqueConstraint('OwnerID')
    )
    op.create_table('LedgerEntry',
    sa.Column('LedgerEntryID', sa.Integer(), nullable=False),
    sa.Column('ExternalID', sa.String(length=36), nullable=False),
    sa.Column('Amount', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('ReceiverCompanyID', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['ReceiverCompanyID'], ['Company.CompanyID'], name='fk_LedgerEntry_ReceiverCompanyID'),
    sa.PrimaryKeyConstraint('LedgerEntryID')
    )
    op.create_table('CheckTransactionDetails',
    sa.Column('LedgerEntryID', sa.Integer(), nullable=False),
    sa.Column('SenderAuthority', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['LedgerEntryID'], ['LedgerEntry.LedgerEntryID'], name='fk_CheckTransactionDetails_LedgerEntryID'),
    sa.PrimaryKeyConstraint('LedgerEntryID')
    )
    op.create_table('CompanyTransactionDetails',
    sa.Column('LedgerEntryID', sa.Integer(), nullable=False),
    sa.Column('SenderCompanyID', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['LedgerEntryID'], ['LedgerEntry.LedgerEntryID'], name='fk_CompanyTransactionDetails_LedgerEntryID'),
    sa.ForeignKeyConstraint(['SenderCompanyID'], ['Company.CompanyID'], name='fk_CompanyTransactionDetails_SenderCompanyID'),
    sa.PrimaryKeyConstraint('LedgerEntryID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_transaction_details',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('from_company_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['from_company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['id'], ['ledger_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('owner', sa.INTEGER(), server_default=sa.text("'-1'"), nullable=False),
    sa.Column('balance', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_trygd_claim', sa.DATETIME(), nullable=True),
    sa.Column('trygd_amount', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('owner')
    )
    op.create_table('ledger_entry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('receiver_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('CompanyTransactionDetails')
    op.drop_table('CheckTransactionDetails')
    op.drop_table('LedgerEntry')
    op.drop_table('Company')
    # ### end Alembic commands ###
