"""initial migration

Revision ID: d1c6700eb7e5
Revises: 
Create Date: 2025-09-17 13:13:35.383594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c6700eb7e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Company',
    sa.Column('CompanyID', sa.Integer(), nullable=False),
    sa.Column('ExternalID', sa.String(length=36), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('OwnerID', sa.Integer(), server_default='-1', nullable=False),
    sa.Column('Balance', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('LastTrygdClaim', sa.DateTime(), nullable=True),
    sa.Column('TrygdAmount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('CompanyID'),
    sa.UniqueConstraint('Name'),
    sa.UniqueConstraint('OwnerID')
    )
    op.create_table('LedgerEntry',
    sa.Column('LedgerEntryID', sa.Integer(), nullable=False),
    sa.Column('ExternalID', sa.String(length=36), nullable=False),
    sa.Column('Amount', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('ReceiverCompanyID', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['ReceiverCompanyID'], ['Company.CompanyID'], name='fk_LedgerEntry_ReceiverCompanyID'),
    sa.PrimaryKeyConstraint('LedgerEntryID')
    )
    op.create_table('CheckTransactionDetails',
    sa.Column('LedgerEntryID', sa.Integer(), nullable=False),
    sa.Column('SenderAuthority', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['LedgerEntryID'], ['LedgerEntry.LedgerEntryID'], name='fk_CheckTransactionDetails_LedgerEntryID'),
    sa.PrimaryKeyConstraint('LedgerEntryID')
    )
    op.create_table('CompanyTransactionDetails',
    sa.Column('LedgerEntryID', sa.Integer(), nullable=False),
    sa.Column('SenderCompanyID', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['LedgerEntryID'], ['LedgerEntry.LedgerEntryID'], name='fk_CompanyTransactionDetails_LedgerEntryID'),
    sa.ForeignKeyConstraint(['SenderCompanyID'], ['Company.CompanyID'], name='fk_CompanyTransactionDetails_SenderCompanyID'),
    sa.PrimaryKeyConstraint('LedgerEntryID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CompanyTransactionDetails')
    op.drop_table('CheckTransactionDetails')
    op.drop_table('LedgerEntry')
    op.drop_table('Company')
    # ### end Alembic commands ###
